# Generated by Django 5.1.7 on 2025-04-07 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portadas/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('age', models.CharField(choices=[('A', 'A'), ('7', '7'), ('12', '12'), ('15', '15'), ('18', '18')], max_length=2)),
                ('releaseDate', models.DateField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('videoQuality', models.CharField(choices=[('HD', 'HD'), ('Full HD', 'Full HD'), ('Ultra HD', 'Ultra HD'), ('HDR', 'HDR')], max_length=10)),
                ('cast', models.CharField(max_length=100)),
                ('seasons', models.PositiveIntegerField(blank=True, null=True)),
                ('episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], max_length=10, null=True)),
                ('categoryFilms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFilms.categoryfilms')),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_on', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFilms.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'film')},
            },
        ),
        migrations.CreateModel(
            name='userlistadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFilms.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'film')},
            },
        ),
    ]
