# Generated by Django 5.1.6 on 2025-02-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portadas/')),
                ('age', models.CharField(choices=[('A', 'A'), ('7', '7'), ('12', '12'), ('15', '15'), ('18', '18')], max_length=2)),
                ('releaseDate', models.DateField()),
                ('duration', models.IntegerField()),
                ('videoQuality', models.CharField(choices=[('HD', 'HD'), ('Full HD', 'Full HD'), ('Ultra HD', 'Ultra HD'), ('HDR', 'HDR')], max_length=10)),
                ('director', models.CharField(max_length=100)),
                ('categoryFilms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFilms.categoryfilms')),
            ],
        ),
    ]
