# Generated by Django 5.1.6 on 2025-02-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfilms',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='categoryfilms',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
