# Generated by Django 5.1.6 on 2025-02-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilms', '0002_alter_categoryfilms_options_categoryfilms_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfilms',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='categoryfilms',
            name='order',
        ),
        migrations.AddField(
            model_name='categoryfilms',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
