# Generated by Django 5.1.6 on 2025-02-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilms', '0003_alter_categoryfilms_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='director',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='name',
            new_name='title',
        ),
    ]
