# Generated by Django 5.1.6 on 2025-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFilms', '0004_rename_director_film_cast_rename_name_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(upload_to='media/portadas'),
        ),
    ]
